package pl

fun main() {
    val max = Klasa().x.split("\n").map { it.length }.max()
    println(max);
}

class Klasa {
    val x = "assembly\n" +
            "secular\n" +
            "unfortunate\n" +
            "tumour\n" +
            "restoration\n" +
            "headline\n" +
            "fastidious\n" +
            "helicopter\n" +
            "theater\n" +
            "ignorance\n" +
            "deficit\n" +
            "critical\n" +
            "damage\n" +
            "recognize\n" +
            "blank\n" +
            "formula\n" +
            "experienced\n" +
            "stroke\n" +
            "convenience\n" +
            "braid\n" +
            "attic\n" +
            "applied\n" +
            "reporter\n" +
            "court\n" +
            "pound\n" +
            "friendly\n" +
            "wealth\n" +
            "match\n" +
            "community\n" +
            "government\n" +
            "freighter\n" +
            "church\n" +
            "recording\n" +
            "civilian\n" +
            "undermine\n" +
            "banner\n" +
            "visual\n" +
            "producer\n" +
            "abbey\n" +
            "image\n" +
            "sample\n" +
            "convince\n" +
            "product\n" +
            "rotate\n" +
            "quarrel\n" +
            "sensitivity\n" +
            "beneficiary\n" +
            "important\n" +
            "leaflet\n" +
            "rainbow\n" +
            "valid\n" +
            "colorful\n" +
            "laser\n" +
            "dramatic\n" +
            "snail\n" +
            "referral\n" +
            "happen\n" +
            "recruit\n" +
            "approval\n" +
            "guitar\n" +
            "discreet\n" +
            "difficulty\n" +
            "transmission\n" +
            "thigh\n" +
            "agreement\n" +
            "smart\n" +
            "cream\n" +
            "beautiful\n" +
            "choose\n" +
            "wound\n" +
            "appendix\n" +
            "undress\n" +
            "disclose\n" +
            "unanimous\n" +
            "vague\n" +
            "reduce\n" +
            "detail\n" +
            "condition\n" +
            "factor\n" +
            "misery\n" +
            "consultation\n" +
            "locate\n" +
            "disaster\n" +
            "shelf\n" +
            "receipt\n" +
            "fabricate\n" +
            "clique\n" +
            "helmet\n" +
            "ridge\n" +
            "proportion\n" +
            "ministry\n" +
            "prevalence\n" +
            "concentrate\n" +
            "twitch\n" +
            "resist\n" +
            "drive\n" +
            "disco\n" +
            "bitch\n" +
            "embrace\n" +
            "insurance\n" +
            "opposite\n" +
            "minimize\n" +
            "shiver\n" +
            "scramble\n" +
            "tasty\n" +
            "insert\n" +
            "camera\n" +
            "stroll\n" +
            "precision\n" +
            "rebellion\n" +
            "consciousness\n" +
            "bless\n" +
            "compound\n" +
            "virgin\n" +
            "dozen\n" +
            "governor\n" +
            "delay\n" +
            "state\n" +
            "straight\n" +
            "exile\n" +
            "palace\n" +
            "encourage\n" +
            "revive\n" +
            "store\n" +
            "pedestrian\n" +
            "director\n" +
            "hilarious\n" +
            "sacred\n" +
            "lover\n" +
            "torch\n" +
            "survey\n" +
            "volcano\n" +
            "supply\n" +
            "dimension\n" +
            "listen\n" +
            "indirect\n" +
            "lease\n" +
            "advice\n" +
            "rhetoric\n" +
            "perform\n" +
            "behave\n" +
            "flash\n" +
            "partner\n" +
            "nationalist\n" +
            "slogan\n" +
            "fraction\n" +
            "chance\n" +
            "terrace\n" +
            "degree\n" +
            "carpet\n" +
            "salvation\n" +
            "extract\n" +
            "secretary\n" +
            "moving\n" +
            "sport\n" +
            "situation\n" +
            "distribute\n" +
            "challenge\n" +
            "animal\n" +
            "stick\n" +
            "harvest\n" +
            "child\n" +
            "stress\n" +
            "shallow\n" +
            "suspicion\n" +
            "separate\n" +
            "engine\n" +
            "current\n" +
            "password\n" +
            "shine\n" +
            "drama\n" +
            "diplomat\n" +
            "mother\n" +
            "romantic\n" +
            "reflection\n" +
            "excavate\n" +
            "slide\n" +
            "sheep\n" +
            "theory\n" +
            "identity\n" +
            "relieve\n" +
            "origin\n" +
            "jealous\n" +
            "traction\n" +
            "viable\n" +
            "arrow\n" +
            "eject\n" +
            "rubbish\n" +
            "launch\n" +
            "means\n" +
            "authorise\n" +
            "hallway\n" +
            "harmony\n" +
            "depend\n" +
            "catch\n" +
            "stomach\n" +
            "decide\n" +
            "horoscope\n" +
            "consideration\n" +
            "cycle\n" +
            "counter\n" +
            "fragrant\n" +
            "person\n" +
            "contradiction\n" +
            "learn\n" +
            "relation\n" +
            "courtesy\n" +
            "stunning\n" +
            "copyright\n" +
            "denial\n" +
            "troop\n" +
            "family\n" +
            "courage\n" +
            "elaborate\n" +
            "motivation\n" +
            "routine\n" +
            "society\n" +
            "construct\n" +
            "sleeve\n" +
            "weave\n" +
            "slice\n" +
            "thoughtful\n" +
            "revise\n" +
            "offend\n" +
            "nerve\n" +
            "hobby\n" +
            "justice\n" +
            "cattle\n" +
            "fascinate\n" +
            "episode\n" +
            "sense\n" +
            "poetry\n" +
            "assume\n" +
            "dominate\n" +
            "voucher\n" +
            "ambiguous\n" +
            "talented\n" +
            "forge\n" +
            "venture\n" +
            "ceremony\n" +
            "business\n" +
            "agriculture\n" +
            "agony\n" +
            "build\n" +
            "imposter\n" +
            "record\n" +
            "porter\n" +
            "kitchen\n" +
            "siege\n" +
            "insight\n" +
            "continuation\n" +
            "packet\n" +
            "recover\n" +
            "ignorant\n" +
            "harmful\n" +
            "movie\n" +
            "trend\n" +
            "tumble\n" +
            "break in\n" +
            "interference\n" +
            "scheme\n" +
            "genuine\n" +
            "ratio\n" +
            "season\n" +
            "coast\n" +
            "clash\n" +
            "bulletin\n" +
            "toast\n" +
            "infection\n" +
            "other\n" +
            "safari\n" +
            "tissue\n" +
            "sleep\n" +
            "memorial\n" +
            "stake\n" +
            "overall\n" +
            "import\n" +
            "different\n" +
            "grief\n" +
            "socialist\n" +
            "welfare\n" +
            "supplementary\n" +
            "distort\n" +
            "grimace\n" +
            "defend\n" +
            "central\n" +
            "spill\n" +
            "definite\n" +
            "water\n" +
            "stride\n" +
            "elect\n" +
            "contain\n" +
            "criticism\n" +
            "formation\n" +
            "exploration\n" +
            "philosophy\n" +
            "salmon\n" +
            "avant-garde\n" +
            "offensive"
}